version: '3'
services:
  postgres:
    container_name: postgres_saga
    hostname: postgres
    image: postgres
    ports:
        - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saga_transactions